package highlighting

var UILanguagesMap = map[string]string{
	"bash":        "Bash / Shell",
	"c":           "C",
	"c++":         "C++",
	"cheetah":     "Cheetah",
	"diff":        "Diff",
	"groovy":      "Groovy",
	"haskell":     "Haskell",
	"html":        "HTML",
	"java":        "Java",
	"javascript":  "JavaScript",
	"json":        "JSON",
	"kotlin":      "Kotlin",
	"lua":         "Lua",
	"makefile":    "Makefile",
	"objective-c": "Objective-C",
	"php":         "PHP",
	"python3":     "Python",
	"ruby":        "Ruby",
	"rust":        "Rust",
	"scala":       "Scala",
	"sql":         "SQL",
	"swift":       "Swift",
	"yaml":        "YAML",
}
