name: Publish Release CLI

on:
  push:
    tags:
      - cli/v*

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Set VERSION
        run: |
          echo VERSION=${TAG#cli/v} >> $GITHUB_ENV
        env:
          TAG: ${{ github.ref_name }}
      - name: Build release artifacts
        run: |
          make release-cli
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist/*
